SchlossLab/mikropml

- README.md
> Add Sarah to contributors list

- README.md
> adding Will to contributors

- README.md
This commit adds my name to the README file as a contributor.
> Add my name to address #18

- LICENSE.md
Add Begum's name, date, fix filename misspelling to address #49
> Add Begum's name, date, fix filename misspelling

- CONTRIBUTING.md
Thanks for your contributions to update the instructions, @tomkoset!  
I updated them slightly to make the process easier (`pull` instead of `fetch` & `merge`), merged our two descriptions of the problem, and used the variable `feature-branch-name` throughout the instructions for consistency.
> Correct merging branch to master

- README.md
- code/R/main.R
2 models were on 1 line in the list of model options.
> Fix CLI typo

- README.md
- code/R/main.R
- code/R/model_pipeline.R
- code/R/run_model.R
- code/R/tuning_grid.R
- config/environment.yml
- data/default_hyperparameters.csv
- slurm_array_job.sh
- test/README.md
- Added @agarretto96's directory structure for different modeling experiments - closes #80 
- Fixed Random Forest mtry values (added 500 and 1000)
- Corrected README.md according to changes with dependencies and new changes
> add Ande's directory structure

- .github/workflows/build.yml
- .github/workflows/check.yml
- .github/workflows/test-coverage.yml
- README.Rmd
- README.md
- docs/index.html
- docs/pkgdown.yml
Resolves #105.
Workflows:
- `check`: Runs R-CMD-check on pushes to master for branch protection.
- `build`: Styles R code, renders the README, updates documentation, and builds the docs site on pull requests to master.
- `test-coverage`: Calculates test coverage and sends report to [codecov.io](https://codecov.io/gh/SchlossLab/mikRopML).
> Overhaul github actions workflows

- .github/workflows/check.yml
- README.Rmd
- README.md
- docs/index.html
- docs/pkgdown.yml
- docs/reference/define_cv.html
Working on #131, I noticed that it fails for Ubuntu with R release, but works on R devel. It's probably getting fixed in the next release.
> Update gh-actions with release & devel R versions

- DESCRIPTION
- README.Rmd
- README.md
- docs/index.html
- docs/pkgdown.yml
- docs/reference/check_group.html
- docs/reference/createGroupedDataPartition.html
- docs/reference/define_cv.html
- docs/reference/groupKMultiFolds.html
- man/check_group.Rd
- man/createGroupedDataPartition.Rd
- man/groupKMultiFolds.Rd
Also fix links and make a couple other minor updates. Resolves #102 
Feel free to make edits on this branch @BTopcuoglu @zenalapp!
> Explain the origin of the package name

- R/preprocess_data.R
- R/split_by_group.R
- docs/pkgdown.yml
- docs/reference/define_cv.html
- docs/reference/run_ml.html
- man/run_ml.Rd
If we want to make the preprocess_data function faster in another way it'll take a little more thought.
> Change all apply family functions to select_apply

- .github/CONTRIBUTING.md
- DESCRIPTION
- LICENSE
- README.Rmd
- README.md
- Add list of dependencies to README
- Link to contributing docs & issues from README
- Update license file with all authors (resolves #172)
Resolves some but not all of the checklist in #169
> Update README & LICENSE files

- R/checks.R
- R/utils.R
- docs/pkgdown.yml
- docs/reference/define_cv.html
- docs/reference/get_perf_metric_fn.html
- docs/reference/split_outcome_features.html
- man/split_outcome_features.Rd
dplyr::select_if() has been superseded by using select() + a selection helper. more here: https://dplyr.tidyverse.org/reference/select.html
> Replace dplyr::select_if() with select() & matches()

- R/utils.R
- docs/authors.html
- docs/index.html
- docs/pkgdown.yml
- docs/reference/define_cv.html
- docs/reference/get_hyperparams_list.html
- docs/reference/get_perf_metric_fn.html
- docs/reference/index.html
- docs/reference/otu_mini.html
- docs/reference/otu_small.html
- docs/sitemap.xml
Prefer using dplyr for subsetting instead of base R.
> Use split_outcome_features() in randomize_feature_order()

- R/run_ml.R
- docs/pkgdown.yml
- docs/reference/get_perf_metric_fn.html
- man/run_ml.Rd
- tests/testthat/test-train_model.R
- vignettes/review-responses.md
Review:
https://github.com/openjournals/joss-reviews/issues/3073
Review responses: 
https://github.com/SchlossLab/mikropml/blob/review-responses/vignettes/review-responses.md
Feel free to edit as you see fit!
> Review responses

- NEWS.md
- R/corr_feats.R
- R/feature_importance.R
- docs/pkgdown.yml
- docs/reference/get_corr_feats.html
- docs/reference/get_feature_importance.html
- docs/reference/get_perf_metric_fn.html
- man/get_corr_feats.Rd
- man/get_feature_importance.Rd
- tests/testthat/test-corr_feats.R
- Resolves #265  
- added correlation method option to get_corr_feats, group_correltated_features, and get_feature_importance
> Add option for correlation method

- NEWS.md
- README.Rmd
- README.md
- docs/index.html
- docs/pkgdown.yml
- docs/reference/get_perf_metric_fn.html
- Added a link in the README to Pat's ML video playlist.
- ~[ ] Write unit tests for any new functionality.~
- ~[ ] Update roxygen comments & vignettes if there are any API changes.~
- Fails on Windows R devel but succeeds for all others.
> Link to @pschloss' ML playlist on YouTube

- .github/workflows/check.yml
- .github/workflows/pr_build.yml
- README.Rmd
- README.md
- docs/index.html
- docs/pkgdown.yml
- docs/pull_request_template.html
- docs/reference/get_feature_importance.html
- docs/reference/get_perf_metric_fn.html
Because everybody else is doing it: https://github.com/github/renaming
- Renamed the `master` branch to `main` on GitHub.
- Updated references to the branch in GitHub Actions workflows & associated links in the README.
- ~[x] Write unit tests for any new functionality or bug fixes.~
- ~[ ] Update roxygen comments & vignettes if there are any API changes.~
- ~[ ] Update `NEWS.md` if this includes any user-facing changes.~
> Rename branch 'master' to 'main'

- NEWS.md
- R/feature_importance.R
- docs/pkgdown.yml
- docs/reference/get_feature_importance.html
- docs/reference/get_perf_metric_fn.html
- docs/reference/randomize_feature_order.html
- man/get_feature_importance.Rd
Strongly recommend using multiple cores.
- ~[ ] Write unit tests for any new functionality or bug fixes.~
- ~[ ] Update docs if there are any API changes:~
- ~[ ] vignettes~
- oldrel is failing and that's ok.
> Improve feature importance examples

- tests/testthat/test-plot.R
- Resolves #351.
- unnamed some test objects
> Fix test for upcoming ggplot2 version
